### ISSUE TITLE
@color of method isn't merged to @color of the class

### ISSUE THREAD

**Issue by unserialize** [VKCOM/nocolor#3]
**Describe the bug**
I have a class with `@color` and its method with another `@color`. 
I expect the method to have both colors (in order class-color + method-color), but it works somehow differently.

**To Reproduce**
PHP code
```php
/** @color controller */
class Controller {
  /** @color allow-model-call */
  static function act() {
    Model::act();
  }
}

/** @color model */
class Model {
  static function act() {}
}
```
palette.yaml
```yaml
demo:
- controller model: restricted dependency
- controller allow-model-call model: ""
```

**Expected behavior**
No error (the second rule should be matched);

**Actual behavior**
An error (the first rule is matched)
BTW, if I add `@color allow-model-call ` as a second color to the `Controller` class itself, everything works as expected. So, the problem is only in class+method case.
